/*
 * @Author: benchenchuang benchenchuang
 * @Date: 2023-11-19 22:18:46
 * @LastEditors: benchenchuang benchenchuang
 * @LastEditTime: 2023-11-19 22:18:55
 * @FilePath: /next-app/src/app/views/dashboard/page.tsx
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
import React from 'react';
import { Button } from 'antd';

export const metadata = {
    title: {
        default:'Dashboard',
    },
    description: 'Generated by Next.js',
}

const Dashboard = () => {

    return (
        <>
            <button>Button</button>
            <Button type="primary">Button</Button>
        </>
    )
}

export default Dashboard